### ISSUE TITLE
Unable to open "Options" on Win 8, FF

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molecule-shapes-basics#1]
I've tested on the two Win 8 devices we have and was unable to activate projector mode because clicking on options did not do anything. They are both running FF 35.0.1. I believe I've seen this happen in another sim where I couldn't go full screen (another thing in the little pop up menu), but I can't remember which sim it was.

Troubleshooting information:
Name: Molecule Shapes: Basics
URL: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes-basics/1.0.0-rc.1/molecule-shapes-basics_en.html
Version: 1.0.0-dev.8
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Language: en-US
Window: 1366x631
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by jonathanolson** [comment]
X bounds are oscillating between 12.209967873313204,115.59329917214133 and 12.20996787331321,115.59329917214134 while trying to center the dialog's title, while setting center 63.90163352272727.

Will try to set up an easy way to reproduce.

**Comment by jonathanolson** [comment]
Example showing numerical oscillation, works in any browser:

``` js
var rect = scenery.Rectangle.bounds( new dot.Bounds2( 0, -27.30000114440918, 103.38333129882812, 6.44999885559082 ), { fill: 'red' } );
rect.centerX = 63.90163352272727;
var a = rect.bounds.copy();
rect.centerX = 63.90163352272727;
var b = rect.bounds.copy();
rect.centerX = 63.90163352272727;
var c = rect.bounds.copy();
rect.centerX = 63.90163352272727;
var d = rect.bounds.copy();

// all true
!a.equals( b );
!c.equals( d );
a.equals( c );
b.equals( d );
```

**Comment by jonathanolson** [comment]
It's a combination of our centerX update AND the fact that the current transform is being applied to bounds. Here's an example without a Scenery dependency:

``` js
var idealCenter = 63.90163352272727;
var minx = 0;
var maxx = 103.38333129882812;
var mx1 = 12.209967873313204;
var mx2 = mx1 + ( idealCenter - ( ( maxx + mx1 ) + ( minx + mx1 ) ) / 2 );
var mx3 = mx2 + ( idealCenter - ( ( maxx + mx2 ) + ( minx + mx2 ) ) / 2 );
var mx4 = mx3 + ( idealCenter - ( ( maxx + mx3 ) + ( minx + mx3 ) ) / 2 );
mx1 // 12.209967873313204
mx2 // 12.20996787331321
mx3 // 12.209967873313204
mx4 // 12.20996787331321
```

**Comment by jonathanolson** [comment]
Also note that if the transform application (here just using +mx1) could be rolled out, this expression can be simplified to the following that works:

``` js
var idealCenter = 63.90163352272727;
var minx = 0;
var maxx = 103.38333129882812;
var mx1 = 12.209967873313204;
var mx2 = mx1 + idealCenter - mx1 - ( maxx + minx ) / 2;
var mx3 = mx2 + idealCenter - mx2 - ( maxx + minx ) / 2;
var mx4 = mx3 + idealCenter - mx3 - ( maxx + minx ) / 2;
mx1 // 12.209967873313204
mx2 // 12.209967873313204
mx3 // 12.209967873313204
mx4 // 12.209967873313204
```

**Comment by jonathanolson** [comment]
Note that "idealCenter - ( max + min ) / 2" is the simplification here, but won't work with transforms that have scale / rotation.

**Comment by jonathanolson** [comment]
Was fixed in the referenced Scenery commit.
