### ISSUE TITLE
is it OK to not use the 'default' ColorProfile?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-shapes-basics#13]
When I changed the API for ProjectorModeCheckbox in https://github.com/phetsims/joist/issues/569, I discovered that `MoleculeShapesColorProfile` has 3 profiles: 'default', 'projector', and 'basics'.  This sim ignores 'default' and uses the other 2 profiles, and that creates complications like: 

(1) Since the `colorProfile` query parameter defaults to 'default', code like this is needed in molecule-shapes-basics-main, which silent ignores errors like `?colorPrrofile=foo`:

```js
  // Set the initial color profile, ignoring anything other than 'basics' or 'projector'.
  if ( phet.chipper.queryParameters.colorProfile === ColorProfile.PROJECTOR_COLOR_PROFILE_NAME ) {
    MoleculeShapesColorProfile.profileNameProperty.value = phet.chipper.queryParameters.colorProfile;
  }
  else {
    MoleculeShapesColorProfile.profileNameProperty.value = DEFAULT_COLOR_PROFILE_NAME;
  }
```

(2) It required adding a `defaultColorProfileName` option to ProjectorModeCheckbox, so that we know which 2 profiles to switch between.

As @jessegreenberg said in https://github.com/phetsims/joist/issues/569#issuecomment-515250918:
> I understand why it was added but think it would be better without this. Shoudl we change MoleculeShapesColorProfile (use basics colors as default colors in a new MoleculeShapesBasicsColorProfile) instead of changing the API?

I replied in https://github.com/phetsims/joist/issues/569#issuecomment-515794317:
> The 'projector' profile for the 2 sims is currently identical. So if we do what you've proposed, then MoleculeShapesColorProfile and MoleculeShapesBasicsColorProfile will duplicate colors for the 'projector' profile, and keeping them in sync would require changing both ColorProfile subclasses. That said, I prefer the current solution. It would be good to get @jonathanolson's input, since he's the author of MoleculeShapesColorProfile.

Assigning to @jonathanolson for comment.

**Comment by jonathanolson** [comment]
Would an abstraction to separate the declaration of color profiles and their uses help? E.g. if the sim-shared color profiles were declared in one place, and each sim decided what to use as its default and projector profile?

**Comment by pixelzoom** [comment]
If the color profiles were separated, I'm afraid that would lead to misspelling errors like `controlPanelBorder` vs `controlPanelBroder`.   I'm inclined to leave things that way they are, if we could clean up issue (1) in https://github.com/phetsims/molecule-shapes-basics/issues/13#issue-474197205.

**Comment by jonathanolson** [comment]
I'm trying to determine if this issue is relevant anymore, it looks like the color profiles are specified in package.json, and things look standardized. Thoughts?

**Comment by pixelzoom** [comment]
Agree, this issue doesn't seem relevant now that we've switched to ProfileColorProperty.   There is a problem with ProfileColorProperty if you don't provide 'default', but tracking that in https://github.com/phetsims/scenery-phet/issues/709.

Closing.
