### ISSUE TITLE
First Load of Model Screen Has Slow atoms

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes-basics#14]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For ES6 Testing. Doesn't seem to occur in published or in the non-basics version of the sim from what I've seen.
Upon the first load of the model screen, when the two bonded atoms are coming in, they are quite laggy and jumpy. This doesn't seem to happen on a reset all or even a refresh of the sim, so it seems to be affected by the cache. As such, test this in incognito to reproduce.

**Visuals**
![judderadd](https://user-images.githubusercontent.com/41024075/75799861-f1d2df00-5d35-11ea-9793-c6706a70e004.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Molecule Shapes: Basics‬
URL: http://phettest.colorado.edu/molecule-shapes-basics/build/phet/molecule-shapes-basics_en_phet.html
Version: 1.3.0-dev.0 2020-03-03 16:44:32 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jonathanolson** [comment]
<img width="1527" alt="Screen Shot 2020-03-05 at 11 05 07 AM" src="https://user-images.githubusercontent.com/480878/76011108-43fc3780-5ed1-11ea-8468-1ca08178b336.png">

Confirmed, but also the cause of what is slowing things down isn't showing in the devtools easily. @ariel-phet, priority? This could be tricky to track down.

**Comment by ariel-phet** [comment]
@jonathanolson I would say "medium'ish" priority

It would be good to know if this issue is sim specific (as in, could the underlying issue affect other sims in the future with ES6), and also we would not want the issue sneaking in for the case of a maintenance release.

**Comment by arouinfar** [comment]
@jonathanolson this issue looks pretty stale to me and I don't think it came up in testing this spring. I'm going to remove the blocks-publication tag, since I don't think it should block the upcoming release.

**Comment by jonathanolson** [comment]
It looked like shaders were being compiled on the first screenview step (i.e. when you open the screen). Commit above forces this earlier on the simulation load. @KatieWoe can you try this out? It seems to make the performance much smoother on my end.

**Comment by KatieWoe** [comment]
It looks smoother to me too I think

**Comment by jonathanolson** [comment]
Thanks! @arouinfar can you see if performance is satisfactory?

**Comment by arouinfar** [comment]
@jonathanolson the performance in the latest RC looks good in macOS 12.0.1 in Chrome & Safari. Not sure if this needs to be verified in the next QA cycle or if it can be closed out, so back to @jonathanolson.

**Comment by jonathanolson** [comment]
I'll note it for the next QA cycle.
