### ISSUE TITLE
Uninstrument elements irrelevant to basics version

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecule-shapes-basics#16]
Discovered while working on phetioFeatured overrides for #15.

I noticed several elements in the tree that are irrelevant to the basics version. They should be uninstrumented or otherwise removed from the tree.

- [x] `*.model.showElectronGeometryProperty`
- [x] `*.model.showLonePairsProperty`
- [x] `modelScreen.view.lonePairPanel`
- [x] `*.view.namePanel.electronGeometryCheckbox`
- [x] `*.view.optionsPanel.showLonePairsCheckbox`
- [x] `realMoleculesScreen.model.showRealViewProperty`
- [x] `global.model.shoeOuterLonePairsProperty`

Note that I did not include `model.electronGeometryProperty` in this list. The electron geometry is not displayed to users; however, it may still be useful in the data stream.

**Comment by jonathanolson** [comment]
Implemented above, can you verify?

**Comment by arouinfar** [comment]
Looks good, thanks @jonathanolson!
