### ISSUE TITLE
sim has no strings file

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-shapes-basics#2]
Sim has no strings file, and molecule-shapes-basics.name lives in molecules-shapes, where it's not used. This is also causing the grunt 'generate README' tasks to fail.  I also suspect that lack of a strings file may be an eventual issue for Rosetta.

**Comment by pixelzoom** [comment]
Fixed, assigned to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
