### ISSUE TITLE
Inccorect Molecular Symbol Displayed

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molecule-shapes-basics#3]
This would be considered a sighting, but there were a couple of times while testing on an iPad 2 (iOS 8) where the drop down list in the Real Molecules screen would show I'm on BeCl2 after switching to SF6. The sim would be showing angles and geometry correctly for SF6; it was only the box saying I was viewing BeCl2 that was incorrect. I cannot figure out a way to reproduce this, but I have definitely had it happen a handful of times.

![img_0021](https://cloud.githubusercontent.com/assets/5863899/6716643/79d6b9e4-cd6c-11e4-955c-92c2f005b957.PNG)

**Comment by jonathanolson** [comment]
Trying to fuzz with https://github.com/phetsims/molecule-shapes/commit/35b01fde5a5bee7fc2249c46010a51be06b1c471 to detect cases where this happens, but it hasn't occurred in 15 minutes. @phet-steele, it would be helpful if possible to spend some extra time to find a reliable way to trigger this (if that's possible).

**Comment by jonathanolson** [comment]
So far unable to trigger on the iPad 3. Will plan to publish with this as a potential issue.

**Comment by ariel-phet** [comment]
Assigning back to @phet-steele 

@phet-steele - we are going to publish with this issue still possible. @jonathanolson was not able to get any leads, would be great if you spent an hour or so at some point seeing if you can find a repeatable way to trigger the bug.

**Comment by phet-steele** [comment]
Alright @jonathanolson, I just spent a...frustrating..hour on this. I could not for the life of me get this to happen on an iPad 2 iOS 9.2 (Tycho) with 1.1.0-rc.2. So...I'm bringing down the issue closing hammer on this one.
