### ISSUE TITLE
Build fails.  It is looking for three r68

### ISSUE THREAD

**Issue by samreid** [phetsims/molecule-shapes-basics#6]
Running "after-requirejs-build" task
Warning: ENOENT, no such file or directory '../sherpa/lib/three-r68.js' Use --force to continue.

Aborted due to warnings.

Looks like this needs to be updated like molecule-shapes was.

**Comment by samreid** [comment]
Fixed at least part of the issue above (it builds now).  @jonathanolson anything else?

**Comment by jonathanolson** [comment]
This was all fixed for the RC, closing.
