### ISSUE TITLE
Text box in stringTest long can cover part of molecule

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/molecule-shapes-basics#7]
Test device: Bates

Operating System: Win 7

Browser: Firefox

Problem description: When using stringTest=long, in the real molecules section, the text box that normally says "show bond angles" is large enough where it can cover up part of the molecule, and the molecule can't be clicked through the box. On the model side, the text size adjusts and this problem is not present. 

Steps to reproduce: Use stringTest=long, go to the real molecules section, and use PCl5.

Severity: minor

Screenshots:
![capture](https://cloud.githubusercontent.com/assets/11947677/12364509/2c30df08-bb8c-11e5-978a-fe0bdf9f178a.PNG)

Troubleshooting information (do not edit):
Name: 12345678901234567890123456789012345678901234567890
URL: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes-basics/1.1.0-rc.2/molecule-shapes-basics_en.html?stringTest=long
Version: 1.1.0-rc.2 2016-01-14 23:30:17 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0
Language: en-US
Window: 1366x631
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"HEAD"},"axon":{"sha":"5a39ec57","branch":"HEAD"},"babel":{"sha":"6351434f","branch":"master"},"brand":{"sha":"c9282935","branch":"HEAD"},"chipper":{"sha":"72a39f97","branch":"HEAD"},"dot":{"sha":"7a28b1a9","branch":"HEAD"},"joist":{"sha":"fa1196f6","branch":"HEAD"},"kite":{"sha":"4a947119","branch":"HEAD"},"molecule-shapes":{"sha":"74bdad4d","branch":"HEAD"},"molecule-shapes-basics":{"sha":"199cd6ef","branch":"HEAD"},"nitroglycerin":{"sha":"ef8c55a2","branch":"HEAD"},"phet-core":{"sha":"f78b5cfe","branch":"HEAD"},"phetcommon":{"sha":"d712ace0","branch":"HEAD"},"scenery":{"sha":"ace9a1cc","branch":"HEAD"},"scenery-phet":{"sha":"6bed84d9","branch":"HEAD"},"sherpa":{"sha":"ae737ccb","branch":"HEAD"},"sun":{"sha":"982a49b8","branch":"HEAD"},"tandem":{"sha":"873e0387","branch":"HEAD"}}

**Comment by brroberts1231** [comment]
Related to phetsims/tasks#478

**Comment by ariel-phet** [comment]
Addressed, closing
